name: Build ros-tis image

# Controls when the workflow will run
on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  job1:
    name: Build image
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: zhuoqiw/ros-tis:0.14.0
          cache-from: type=registry,ref=zhuoqiw/ros-tis:0.14.0
          cache-to: type=inline
