name: Build ros-tis

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      ubuntu_version:
        description: 'Ubuntu version'
        required: true
        default: '22.04'
        type: choice
        options:
        - '20.04'
        - '22.04'

defaults:
  run:
    shell: bash

jobs:
  job1:
    name: Build image on ${{ github.event.inputs.ubuntu_version }}
    runs-on: ubuntu-${{ github.event.inputs.ubuntu_version }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push on 20.04
        if: github.event.inputs.ubuntu_version == '20.04'
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          build-args: TAG=galactic
          push: true
          tags: zhuoqiw/ros-tis:focal-1.0.0
          cache-from: type=registry,ref=zhuoqiw/ros-tis:focal-1.0.0
          cache-to: type=inline
      -
        name: Build and push on 22.04
        if: github.event.inputs.ubuntu_version == '22.04'
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          build-args: TAG=humble
          push: true
          tags: zhuoqiw/ros-tis:jammy-1.0.0
          cache-from: type=registry,ref=zhuoqiw/ros-tis:jammy-1.0.0
          cache-to: type=inline
